FROM openjdk:8-alpine3.9 AS stage-gradle-build
ARG GITHUB_ACTOR
ARG GITHUB_TOKEN

ENV GITHUB_ACTOR = ${GITHUB_ACTOR}
ENV GITHUB_TOKEN = ${GITHUB_TOKEN}

ADD . .

RUN ./gradlew clean build --stacktrace

FROM openjdk:8-alpine3.9 AS stage-java-run
COPY --from=stage-gradle-build /build/libs/bialydunajec-backend-*.jar bialydunajec-backend.jar

VOLUME /tmp

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/bialydunajec-backend.jar"]