FROM openjdk:8 AS stage-gradle-build
ARG GITHUB_ACTOR
ARG GITHUB_TOKEN

ENV GITHUB_ACTOR = ${GITHUB_ACTOR}
ENV GITHUB_TOKEN = ${GITHUB_TOKEN}

ADD . .

RUN ./gradlew -Prelease build --stacktrace

VOLUME /tmp

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/bialydunajec-backend.jar"]