spring:
  datasource:
    url: "jdbc:h2:mem:h2-local;INIT=create schema if not exists CAMP_REGISTRATIONS \\; create schema if not exists CAMP_EDITION \\; create schema if not exists ACADEMIC_MINISTRY \\; create schema if not exists USERS \\; create schema if not exists EMAIL" #jdbc:h2:file:./h2-local => local database | mem:test in-memory
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true