spring:
  datasource:
    url: "jdbc:mysql://31.186.82.95:3306/m1194_bialydunajec_dev?serverTimezone=CEST"
    username: m1194_bialy_dev
    password: XXXXXX
    initialization-mode: always
    continue-on-error: true
    platform: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
