server:
  port: 4455
spring:
  profiles:
    include:
      - mail_log
      - database_postgresql_dev
      - database_mongo_dev
  mail:
    username: dev.zapisy@bialydunajec.org
    password: 4tFhHO2LseTJ714UV1Q5

bialydunajec:
  oauth2:
    clients:
      - client-id: "web-angular_main-dev"
        client-secret: "BIyZp3vLjtbqMkSLzEGD"
        authorized-grant-types: password, client_credentials, refresh_token
        access-token-validity-seconds: 7776000 # 3600 seconds = 60 minutes
        refresh-token-validity-seconds: 7776000 # 7776000 seconds = 129 600 minutes = 2 160 hours = 90 days
        scopes: allmighty
      - client-id: "web-angular_admin-dev"
        client-secret: "gLuRzxiAJJSL6b1wrIGw"
        authorized-grant-types: password, client_credentials, refresh_token
        access-token-validity-seconds: 7776000 # 3600 seconds = 60 minutes
        refresh-token-validity-seconds: 7776000 # 7776000 seconds = 129 600 minutes = 2 160 hours = 90 days
        scopes: allmighty
  facebook:
    access-token: "EAAD8VBKY89IBAIA1pwlPdGEI6ZC3oDFQCQuZAv4iI9MCj5OZBE9RbxudiFbe7PKx5gOEvFsZCcQDPX8V6UIGb0X2XzafTRhAkA11aLPM7VdCrjQpODp0qQkIbuUgdnjCBPGAAqzzDa4YWqVjV9nBd4vo2tXtwiHsB9RFwiQg8AZDZD"
  frontend:
    main:
      base-url: "https://dev.bialydunajec.org"
      registration-verification-url: "https://dev.bialydunajec.org/zapisy/weryfikacja?zgloszenie=:campParticipantRegistrationId&kod-weryfikacyjny=:verificationCode"
