spring:
  profiles:
    include:
      - database_h2_local_mem
      - mail_send
  mail:
    username: zapisy@bialydunajec.org
    password: 4nhvbu3DGqKc21F3uaOf

bialydunajec:
  oauth2:
    clients:
      - client-id: "web-angular"
        client-secret: "fUMU6AngbLIkfTOAqfifaShzOEMeUQ/cxpij3iwMM30Czj..7ipdLxv6"
        authorized-grant-types: password, client_credentials, refresh_token
        access-token-validity-seconds: 3600 # 3600 seconds = 60 minutes
        refresh-token-validity-seconds: 7776000 # 7776000 seconds = 129 600 minutes = 2 160 hours = 90 days
        scopes: allmighty
      - client-id: "mobile-android"
        client-secret: "AndekfUMU6bLIkfTOAqfifaShzOEMeUQ/cxpij3MobiwMM30Czj..7ipdLxv6"
        authorized-grant-types: password, client_credentials, refresh_token
        access-token-validity-seconds: 3600 # 3600 seconds = 60 minutes
        refresh-token-validity-seconds: 7776000 # 7776000 seconds = 129 600 minutes = 2 160 hours = 90 days
        scopes: allmighty
  frontend:
    main:
      base-url: "https://new.bialydunajec.org"
      registration-verification-url: "https://new.bialydunajec.org/zapisy/weryfikacja?zgloszenie=:campParticipantRegistrationId&kod-weryfikacyjny=:verificationCode"
#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: JadeNaBialy!
#    key-store-type: PKCS12
#    key-alias: tomcat
