spring:
  datasource:
    url: "jdbc:mysql://mysql23.mydevil.net:3306/m1194_bialydunajec_dev"
    username: m1194_bialy_dev
    password: JadeNa35Bialy!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
