server:
  port: 3344
spring:
  profiles:
    include:
      - database_h2_local_mem
      - mail_send
  mail:
    username: zapisy@bialydunajec.org
    password: 4nhvbu3DGqKc21F3uaOf

bialydunajec:
  oauth2:
    clients:
      - client-id: "web-angular_main-prod"
        client-secret: "fUMU6AngbLa!!sdasdIkfTOAqwepij3iwMM30Czj..7ipdLxv6"
        authorized-grant-types: password, client_credentials, refresh_token
        access-token-validity-seconds: 7776000 # 3600 seconds = 60 minutes
        refresh-token-validity-seconds: 7776000 # 7776000 seconds = 129 600 minutes = 2 160 hours = 90 days
        scopes: allmighty
      - client-id: "web-angular_admin-prod"
        client-secret: "IybqweqeGH2FzassdMatqhbW5iadszizlNowiM3R"
        authorized-grant-types: password, client_credentials, refresh_token
        access-token-validity-seconds: 7776000 # 3600 seconds = 60 minutes
        refresh-token-validity-seconds: 7776000 # 7776000 seconds = 129 600 minutes = 2 160 hours = 90 days
        scopes: allmighty
  frontend:
    main:
      base-url: "https://new.bialydunajec.org"
      registration-verification-url: "https://new.bialydunajec.org/zapisy/weryfikacja?zgloszenie=:campParticipantRegistrationId&kod-weryfikacyjny=:verificationCode"
