spring:
  datasource:
    url: "jdbc:mysql://31.186.82.95:3306/m1194_bialydunajec_staging"
    username: m1194_bialy_stag
    password: RTlb9a3ZgmHqVmhAT6zn
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

