spring:
  datasource:
    url: "jdbc:mysql://31.186.82.95:3306/m1194_bialydunajec_prod?useLegacyDatetimeCode=false&serverTimezone=CEST"
    username: m1194_bialy_prod
    password: ENC(xY9wTebt00k1Skn+UjnNRH1OmWHXaFPooxDInAOwLNHGmxuYeWK83g==)
    initialization-mode: always
    continue-on-error: true
    platform: mysql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

