server:
  port: 3344
spring:
  profiles:
    include:
      - database_mysql_prod
      - database_mongo_prod
      - mail_send
  mail:
    username: zapisy@bialydunajec.org
    password: 4nhvbu3DGqKc21F3uaOf

bialydunajec:
  oauth2:
    clients:
      - client-id: "web-angular_main-prod"
        client-secret: "fUMU6AngbLa!!sdasdIkfTOAqwepij3iwMM30Czj..7ipdLxv6"
        authorized-grant-types: password, client_credentials, refresh_token
        access-token-validity-seconds: 7776000 # 3600 seconds = 60 minutes
        refresh-token-validity-seconds: 7776000 # 7776000 seconds = 129 600 minutes = 2 160 hours = 90 days
        scopes: allmighty
      - client-id: "web-angular_admin-prod"
        client-secret: "IybqweqeGH2FzassdMatqhbW5iadszizlNowiM3R"
        authorized-grant-types: password, client_credentials, refresh_token
        access-token-validity-seconds: 7776000 # 3600 seconds = 60 minutes
        refresh-token-validity-seconds: 7776000 # 7776000 seconds = 129 600 minutes = 2 160 hours = 90 days
        scopes: allmighty
  facebook:
    access-token: "EAAD8VBKY89IBAIA1pwlPdGEI6ZC3oDFQCQuZAv4iI9MCj5OZBE9RbxudiFbe7PKx5gOEvFsZCcQDPX8V6UIGb0X2XzafTRhAkA11aLPM7VdCrjQpODp0qQkIbuUgdnjCBPGAAqzzDa4YWqVjV9nBd4vo2tXtwiHsB9RFwiQg8AZDZD"
  google-photos-library-api:
    refresh-token: "1/poWoHFGQd2ppMsJr9XZTxVHl6JvvrfiGnvuc2JoREe4"
    credentials-json-path: ".\\bialydunajec-gallery\\infrastructure\\src\\main\\resources\\credentials.json"
  frontend:
    main:
      base-url: "https://new.bialydunajec.org"
      registration-verification-url: "https://new.bialydunajec.org/zapisy/weryfikacja?zgloszenie=:campParticipantRegistrationId&kod-weryfikacyjny=:verificationCode"
