spring:
  datasource:
    url: "jdbc:mysql://31.186.82.95:3306/m1194_bialydunajec_staging?serverTimezone=CEST"
    username: m1194_bialy_stag
    password: XXXXXX
    initialization-mode: always
    continue-on-error: true
    platform: mysql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

