version: '3.7'

services:
  bialydunajec-backend:
    build:
      context: ../../
      dockerfile: ./docker/ng-serve/backend/Dockerfile
    ports:
      - 6655:3344
    environment:
      SPRING_PROFILES_ACTIVE: env_local_inside_docker
    volumes:
      - "../../backend:/app"
    command: ["gradle", "bootRun"]

  bialydunajec-frontend-main:
    build:
      context: ../../
      dockerfile: ./docker/ng-serve/frontend-main/Dockerfile
    networks:
      - bialydunajec-ng-serve-network
    ports:
      - 4200:4200
    volumes:
      - "/app/node_modules"
      - "../../frontend-main:/app"
    command: ["npm", "run", "start"]

  bialydunajec-frontend-adminpanel:
    build:
      context: ../../
      dockerfile: ./docker/ng-serve/frontend-adminpanel/Dockerfile
    networks:
      - bialydunajec-ng-serve-network
    ports:
      - 4201:4201
    volumes:
      - "/app/node_modules"
      - "../../frontend-adminpanel:/app"
    command: ["npm", "run", "start"]

  bialydunajec-postgres:
    image: library/postgres:11
    restart: always
    ports:
      - 6645:5432
    networks:
      - bialydunajec-ng-serve-network
    environment:
      POSTGRES_DB: bialydunajec-postgres-db
      POSTGRES_USER: bialydunajec-postgres-user
      POSTGRES_PASSWORD: bialydunajec-postgres-password
    volumes:
      - ../../backend/src/main/resources:/docker-entrypoint-initdb.d/
    # - ../bialydunajec-data/pgdata:/var/lib/postgresql/data #keep data outside container

  bialydunajec-mongodb:
    image: library/mongo:4.0
    ports:
      - 6646:27017
    networks:
      - bialydunajec-ng-serve-network
    #volumes:
    #  - ../bialydunajec-data/mongodata:/data/db #keep data outside container


networks:
  bialydunajec-ng-serve-network:
    name: bialydunajec-ng-serve-network
