export enum EventType {
  EMAIL_MESSAGE_CREATED = 'EMAIL_MESSAGE_CREATED',
  EMAIL_MESSAGE_SENT_FAILURE = 'EMAIL_MESSAGE_SENT_FAILURE',
  EMAIL_MESSAGE_SENT_SUCCESS = 'EMAIL_MESSAGE_SENT_SUCCESS',
  CAMP_PARTICIPANT_REGISTERED = 'CAMP_PARTICIPANT_REGISTERED',
  CAMP_PARTICIPANT_CONFIRMED = 'CAMP_PARTICIPANT_CONFIRMED',
  COMMITMENT_PAID = 'COMMITMENT_PAID'
}
