package org.bialydunajec.registrations.domain.academicministry

import org.bialydunajec.ddd.domain.base.persistence.DomainRepository

interface AcademicMinistryRepository : DomainRepository<CampRegistrationsAcademicMinistry, AcademicMinistryId>