export enum TransportType {
  PRIVATE_TRANSPORT = 'PRIVATE_TRANSPORT',
  PRIVATE_CAR = 'PRIVATE_CAR', // TODO: To remove!
  PUBLIC_TRANSPORT = 'PUBLIC_TRANSPORT',
  CAMP_TRANSPORT = 'CAMP_TRANSPORT',
  HITCH_HIKING = 'HITCH_HIKING',
  OTHER_TRANSPORT = 'OTHER_TRANSPORT'
}
