version: 2

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.9.3-browsers
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install local dependencies
          command: npm install
      - run:
          name: Install Angular CLI
          command: sudo npm install -g @angular/cli
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      # Lint the source code
      #- run:
      #    name: Linting
      #    command: npm run lint
      # Test the source code
      #- run:
      #    name: Testing
      #    command: npm run test
      - run:
          name: Build bialydunajec-commons library
          command: ng build bialydunajec-commons
      - run:
          name: Build bialydunajec-admin
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                ng run bialydunajec-admin:build:production
            elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
                ng run bialydunajec-admin:build:staging
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
                ng run bialydunajec-admin:build:development
            else
                ng build bialydunajec-admin
            fi
      - run:
          name: Build bialydunajec-main
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                ng run bialydunajec-main:build:production
            elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
                ng run bialydunajec-main:build:staging
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
                ng run bialydunajec-main:build:development
            else
                ng build bialydunajec-main
            fi
      # Cache the dist folder for the deploy job
      - store_artifacts:
          path: ~/project/dist
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  deploy:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.9.3-browsers
    steps:
      - add_ssh_keys
      # Restore cache from the build job which contains the
      # dist folder that needs to be deployed
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Deploy bialydunajec-main
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                ssh Bialydunajec@31.186.82.95 rm -rf /home/Bialydunajec/domains/new.bialydunajec.org/public_html/*
                scp -r dist/bialydunajec-main Bialydunajec@31.186.82.95:/home/Bialydunajec/domains/new.bialydunajec.org/public_html
            elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
                ssh Bialydunajec@31.186.82.95 rm -rf /home/Bialydunajec/domains/staging.bialydunajec.org/public_html/*
                scp -r dist/bialydunajec-main Bialydunajec@31.186.82.95:/home/Bialydunajec/domains/staging.bialydunajec.org/public_html
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
                ssh Bialydunajec@31.186.82.95 rm -rf /home/Bialydunajec/domains/dev.bialydunajec.org/public_html/*
                scp -r dist/bialydunajec-main Bialydunajec@31.186.82.95:/home/Bialydunajec/domains/dev.bialydunajec.org/public_html
            fi
      - run:
          name: Deploy bialydunajec-admin
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                ssh Bialydunajec@31.186.82.95 rm -rf /home/Bialydunajec/domains/admin.bialydunajec.org/public_html/*
                scp -r dist/bialydunajec-admin Bialydunajec@31.186.82.95:/home/Bialydunajec/domains/admin.bialydunajec.org/public_html
            elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
                ssh Bialydunajec@31.186.82.95 rm -rf /home/Bialydunajec/domains/admin.staging.bialydunajec.org/public_html/*
                scp -r dist/bialydunajec-admin Bialydunajec@31.186.82.95:/home/Bialydunajec/domains/admin.staging.bialydunajec.org/public_html
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
                ssh Bialydunajec@31.186.82.95 rm -rf /home/Bialydunajec/domains/admin.dev.bialydunajec.org/public_html/*
                scp -r dist/bialydunajec-admin Bialydunajec@31.186.82.95:/home/Bialydunajec/domains/admin.dev.bialydunajec.org/public_html
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - staging
                - master
