spring:
  datasource:
    url: "jdbc:postgresql://31.186.82.95:5432/p1194_bialy_dev"
    username: p1194_bialy_dev
    password: XXXXXX
    initialization-mode: always
    continue-on-error: true
    platform: postgresql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
