server:
  port: 3344
spring:
  profiles:
    include:
      - database_h2_local_mem
      - mail_log
  mail:
    username: dev.zapisy@bialydunajec.org
    password: XXXXXX

bialydunajec:
  oauth2:
    clients:
      - client-id: "web-angular_main-local-inside-docker"
        client-secret: "web-angular_main-local-inside-docker-secret"
        authorized-grant-types: password, client_credentials, refresh_token
        access-token-validity-seconds: 7776000 # 3600 seconds = 60 minutes
        refresh-token-validity-seconds: 7776000 # 7776000 seconds = 129 600 minutes = 2 160 hours = 90 days
        scopes: allmighty
      - client-id: "web-angular_admin-local-inside-docker"
        client-secret: "web-angular_admin-local-inside-docker-secret"
        authorized-grant-types: password, client_credentials, refresh_token
        access-token-validity-seconds: 7776000 # 3600 seconds = 60 minutes
        refresh-token-validity-seconds: 7776000 # 7776000 seconds = 129 600 minutes = 2 160 hours = 90 days
        scopes: allmighty
  facebook:
    access-token: "XXXXXX"
  camp-gallery-provider: "empty" # empty / google-photos
  google-photos-library-api:
    refresh-token: "XXXXXX"
    credentials-json-path: google-services\google-photos\credentials.json
  frontend:
    main:
      base-url: "http://localhost:4201"
      registration-verification-url: "http://localhost:4201/zapisy/weryfikacja?zgloszenie=:campParticipantRegistrationId&kod-weryfikacyjny=:verificationCode"
