structurizr:
  workspace:
    id: 47771
    name: BialyDunajec-WebApp
    description: Architektura aplikacji webowej dla Obozu Adaptacyjnego Duszpasterstw Akademickich Wrocławia i Opola w Białym Dunajcu
    key: 46124922-670a-488e-9937-4a704261b5ab
    secret: 68c6b78f-eeb1-493f-891e-3127f6b505c1