package org.bialydunajec.gradle

object Versions {
    const val archUnitVersion = "0.9.3"
    const val arrowVersion = "0.8.2"
    const val assertjVersion = "3.12.2"
    const val assertkVersion = "0.17"
    const val axonFrameworkVersion = "4.0.3"
    const val googleApiClientVersion = "1.30.2"
    const val googleAuthLibraryOauth2HttpVersion = "0.16.2"
    const val googlePhotosLibraryClientVersion = "1.2.0"
    const val groovyVersion = "3.0.4"
    const val jasyptVersion = "2.1.1"
    const val jaxbApiVersion = "2.3.0"
    const val jfairyVersion = "0.6.2"
    const val jUnitVersion = "5.3.2"
    const val ktTimeTravelerVersion = "0.1.2"
    const val mockkVersion = "1.9.3"
    const val mysqlConnectorVersion = "8.0.15"
    const val oAuth2AutoconfigureVersion = "2.1.3.RELEASE"
    const val postgresqlConnectorVersion = "42.2.5"
    const val restfbVersion = "2.12.0"
    const val rxJavaVersion ="2.2.0"
    const val rxRelayVersion = "2.1.0"
    const val spekVersion = "2.0.6"
    const val spockVersion = "2.0-M3-groovy-3.0"
    const val swaggerVersion = "2.9.2"
}
