name: "🚀 Backend pipeline"

on:
  push
  paths-ignore:
    - '**/README.md'

jobs:
  build-jar:
    name: "Build application & start in docker-compose"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/backend/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run tests with Gradle
        uses: eskatos/gradle-command-action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: -p backend -Prelease test
          wrapper-directory: ./backend
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: -p backend -Prelease build -x test
          wrapper-directory: ./backend
      - name: Validate if docker-compose.local.yaml can run
        if:   github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/master'
        run: |
          cd ./backend
          docker-compose -f docker-compose.local.yml --log-level INFO up -d
      - name: Change artifact name
        run:  cp ./backend/build/libs/bialydunajec-backend* ./backend/build/libs/bialydunajec-backend.jar
      - uses: actions/upload-artifact@v1
        name: Upload artifact bialydunajec-backend.jar
        with:
          name: bialydunajec-backend.jar
          path: ./backend/build/libs/bialydunajec-backend.jar
      - uses: actions/upload-artifact@v1
        name: Upload artifact Dockerfile
        with:
          name: Dockerfile
          path: ./backend/Dockerfile

  push-docker-image:
    name: "Push docker image to GitHub"
    if:   github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/master'
    needs: build-jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: bialydunajec-backend.jar
          path: ./backend/build/libs/bialydunajec-backend.jar
      - uses: actions/download-artifact@v2
        with:
          name: Dockerfile
          path: ./backend
      - name: Push docker image to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: nowakprojects/bialydunajec-kotlin-backend/bialydunajec-backend
          path: ./backend
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true

#    - name: Deploy application
#      uses: appleboy/scp-action@master
#      env:
#        HOST: ${{ secrets.HOST }}
#        USERNAME: ${{ secrets.USER }}
#        KEY: ${{ secrets.PRIVATE_KEY }}
#      with:
#        source: "build/libs/bialydunajec-backend.jar"
#        target: "/home/Bialydunajec/webapp/temp-backend/env_dev"
#        strip_components: 2
#    - name: Run deployed version
#      uses: appleboy/ssh-action@master
#      with:
#        username: ${{ secrets.USER }}
#        host: ${{ secrets.HOST }}
#        key: ${{ secrets.PRIVATE_KEY }}
#        script_stop: true
#        script: |
#          pkill -f backend/env_dev
#          rm -rf /home/Bialydunajec/webapp/backend/env_dev/*
#          mv /home/Bialydunajec/webapp/temp-backend/env_dev/bialydunajec-backend.jar /home/Bialydunajec/webapp/backend/env_dev/
#          nohup java -jar -D-Xms512m -Xmx512m -Dspring.profiles.active=env_dev /home/Bialydunajec/webapp/backend/env_dev/bialydunajec-backend.jar &> nohup_dev.out&
