name: "Build Spring Boot JAR for bialydunajec-kotlin-backend"

on:
  push:
    branches-ignore:
      - master
      - staging
      - develop
      - heroku
      - feature/#133_modularmonolith
      - feature/backend-folder

jobs:
  build-jar:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Gradle | bialydunajec-ddd-domain | Build
      run: ./gradlew -Prelease bialydunajec-ddd:bialydunajec-ddd-domain:build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Gradle | bialydunajec-ddd-dto | Build
      run: ./gradlew -Prelease bialydunajec-ddd:bialydunajec-ddd-dto:build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Gradle | bialydunajec-ddd-application | Build
      run: ./gradlew -Prelease bialydunajec-ddd:bialydunajec-ddd-application:build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Gradle | bialydunajec-ddd-presentation | Build
      run: ./gradlew -Prelease bialydunajec-ddd:bialydunajec-ddd-presentation:build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Gradle | bialydunajec-ddd-infrastructure | Build
      run: ./gradlew -Prelease bialydunajec-ddd:bialydunajec-ddd-infrastructure:build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Gradle | WHOLE APPLICATION bialydunajec-kotlin-backend | Build
      run: ./gradlew -Prelease build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Change artifact name
      run:  cp build/libs/bialydunajec-backend* build/libs/bialydunajec-backend.jar

    - uses: actions/upload-artifact@v1
      name: Upload artifact
      with:
        name: bialydunajec-backend.jar
        path: ./build/libs/bialydunajec-backend.jar