name: Build Spring Boot JAR

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests with Gradle
      run: ./gradlew -Prelease test
    - name: Build with Gradle
      run: ./gradlew -Prelease build -x test
#    - name: change artifact name
#      run:  cp build/libs/bialydunajec-backend* build/libs/bialydunajec-backend.jar
#    - name: Deploy dev version
#      uses: appleboy/scp-action@master
#      env:
#        HOST: ${{ secrets.HOST }}
#        USERNAME: ${{ secrets.USER }}
#        KEY: ${{ secrets.PRIVATE_KEY }}
#      with:
#        source: "build/libs/bialydunajec-backend.jar"
#        target: "/home/Bialydunajec/webapp/temp-backend/env_dev"
#        strip_components: 2
#    - name: Run deployed version
#      uses: appleboy/ssh-action@master
#      with:
#        username: ${{ secrets.USER }}
#        host: ${{ secrets.HOST }}
#        key: ${{ secrets.PRIVATE_KEY }}
#        script_stop: true
#        script: |
#          pkill -f backend/env_dev
#          rm -rf /home/Bialydunajec/webapp/backend/env_dev/*
#          mv /home/Bialydunajec/webapp/temp-backend/env_dev/bialydunajec-backend.jar /home/Bialydunajec/webapp/backend/env_dev/
#          nohup java -jar -D-Xms512m -Xmx512m -Dspring.profiles.active=env_dev /home/Bialydunajec/webapp/backend/env_dev/bialydunajec-backend.jar &> nohup_dev.out&
