name: "Build Spring Boot JAR for bialydunajec-kotlin-backend & deploy on production environment"

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Change directory to backend
      run: cd backend
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Run tests with Gradle
      run: ./gradlew -Prelease test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build with Gradle
      run: ./gradlew -Prelease build -x test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Change artifact name
      run:  cp build/libs/bialydunajec-backend* build/libs/bialydunajec-backend.jar
    - uses: actions/upload-artifact@v1
      name: Upload artifact
      with:
        name: bialydunajec-backend.jar
        path: ./build/libs/bialydunajec-backend.jar
    - name: Push docker image to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: nowakprojects/bialydunajec-kotlin-backend/bialydunajec-backend
        tag_with_ref: true
        tag_with_sha: true
        add_git_labels: true

#    - name: Deploy application
#      uses: appleboy/scp-action@master
#      env:
#        HOST: ${{ secrets.HOST }}
#        USERNAME: ${{ secrets.USER }}
#        KEY: ${{ secrets.PRIVATE_KEY }}
#      with:
#        source: "build/libs/bialydunajec-backend.jar"
#        target: "/home/Bialydunajec/webapp/temp-backend/env_prod"
#        strip_components: 2
#    - name: Run deployed version
#      uses: appleboy/ssh-action@master
#      with:
#        username: ${{ secrets.USER }}
#        host: ${{ secrets.HOST }}
#        key: ${{ secrets.PRIVATE_KEY }}
#        script_stop: true
#        script: |
#          pkill -f backend/env_prod
#          rm -rf /home/Bialydunajec/webapp/backend/env_prod/*
#          mv /home/Bialydunajec/webapp/temp-backend/env_prod/bialydunajec-backend.jar /home/Bialydunajec/webapp/backend/env_prod/
#          nohup java -jar -D-Xms512m -Xmx512m -Dspring.profiles.active=env_prod /home/Bialydunajec/webapp/backend/env_prod/bialydunajec-backend.jar &> nohup_dev.out&
