name: "Build Spring Boot JAR for bialydunajec-kotlin-backend"

on:
  push:
    branches-ignore:
      - master
      - staging
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests with Gradle
      run: ./gradlew -Prelease test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build with Gradle
      run: ./gradlew -Prelease build -x test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
