name: "Build Spring Boot JAR for bialydunajec-kotlin-backend"

on:
  push:
    branches-ignore:
      - master
      - staging
      - develop
      - heroku
      - feature/#133_modularmonolith

defaults:
  run:
    working-directory: backend

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests with Gradle
      run: ./gradlew -Prelease test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build with Gradle
      run: ./gradlew -Prelease build -x test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Change artifact name
      run:  cp build/libs/bialydunajec-backend* build/libs/bialydunajec-backend.jar
    - uses: actions/upload-artifact@v1
      name: Upload artifact
      with:
        name: bialydunajec-backend.jar
        path: .backend/build/libs/bialydunajec-backend.jar