name: "Build Spring Boot JAR for bialydunajec-kotlin-backend"

on:
  push:
    branches-ignore:
      - master
      - staging
      - develop
      - heroku
      - feature/#133_modularmonolith

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/backend/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run tests with Gradle
        uses: eskatos/gradle-command-action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: -p backend -Prelease test
          wrapper-directory: ./backend
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: -p backend -Prelease build -x test
          wrapper-directory: ./backend
      - name: Change artifact name
        run:  cp ./backend/build/libs/bialydunajec-backend* ./backend/build/libs/bialydunajec-backend.jar
      - uses: actions/upload-artifact@v1
        name: Upload artifact
        with:
          name: bialydunajec-backend.jar
          path: ./backend/build/libs/bialydunajec-backend.jar
      - uses: actions/upload-artifact@v1
        name: Upload artifact - application Dockerfile
        with:
          name: Dockerfile
          path: ./backend/Dockerfile