name: "Build docker-compose for local development"

on:
  push:
    branches-ignore:
      - master
      - staging
      - develop
      - heroku

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Validate if docker-compose.local.yaml can run
      run: |
        cd ./backend
        docker-compose -f docker-compose.local.yml --log-level INFO up -d
