name: "Build Spring Boot JAR for bialydunajec-kotlin-backend"

on:
  push:
    branches-ignore:
      - master
      - staging
      - develop
      - heroku

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests with Gradle
      uses: eskatos/gradle-command-action@v1.3.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        arguments: -Prelease test
    - name: Build with Gradle
      uses: eskatos/gradle-command-action@v1.3.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        arguments: -Prelease build -x test
    - name: Change artifact name
      run:  cp build/libs/bialydunajec-backend* build/libs/bialydunajec-backend.jar
    - uses: actions/upload-artifact@v1
      name: Upload artifact
      with:
        name: bialydunajec-backend.jar
        path: ./build/libs/bialydunajec-backend.jar