name: Heroku Awake

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: "http://bialydunajec-backend.herokuapp.com:3344/swagger-ui.html"